services:
  web:
    build: .
    container_name: qpay
    restart: always
    ports:
      - "8080:80"
    environment:
      - SITE_URL=https://your-domain.com
      - PAY_DOMAIN=https://pay.example.com
      - MERCHANT_ID=1000
      - API_KEY=xxxxxxxxxxxxxxxxxxxxxx